repository: redis
fullnameOverride: redis

nodeSelector:
  kubernetes.io/hostname: "node1"

auth:
  enabled: false
  password: qwe

redis:
  replicaCount: 2
  image:
    repository: redis-stack-server
    tag: 7.4.0-v5
    pullPolicy: IfNotPresent
  service:
    port: 6379
  resources:
    requests:
      cpu: 8
      memory: 8Gi
    limits:
      cpu: 8
      memory: 8Gi

sentinel:
  enabled: true
  image:
    repository: redis-stack-server
    tag: 7.4.0-v5
    pullPolicy: IfNotPresent
  service:
    port: 26379
  master: mymaster
  quorum: 2
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 1
      memory: 512Mi
